author: 
  name: Hudsen Mickley
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/usenamethatisnttaken" }
theme: minima
title: Projects Portfolio
description: A collection of all of my moderately big+ projects